language: node_js
node_js:
- '8'
branchs:
  only:
  - master
install:
- npm install
script:
- npm run build
addons:
  ssh_known_hosts:
  - 139.199.90.74
after_success:
- chmod 600 ~/.ssh/id_rsa
- ssh blog@139.199.90.74 -o StrictHostKeyChecking=no 'cd ~/blog-front && git pull
  && npm install && npm run build'
before_install:
- openssl aes-256-cbc -K $encrypted_3a6cd1990fd4_key -iv $encrypted_3a6cd1990fd4_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
